#-------------------------------
# General Site Settings
baseurl: ""# the subpath of your site, e.g. /blog
#url: "" # the base hostname & protocol for your site, e.g. http://example.com

domain: https://enexaproject.github.io     # if you want to force HTTPS, specify the domain without the http at the start, e.g. example.com
url: https://enexaproject.github.io # the base hostname and protocol for your site, e.g. http://example.com


#-------------------------------
# Build Settings
markdown: kramdown
permalink: /:title
plugins:
  - jekyll-paginate
  - jekyll-sitemap

paginate: 7
paginate_path: "/blog/page/:num"


#-------------------------------
# Collections
collections:
  pages:
    output: true
    permalink: /:name
  posts:
    output: true
    permalink: /blog/:slug
  authors:
    output: true
    permalink: /members/:name

# Pages Path
defaults:
  - scope:
      path: ""
    values:
      layout: "default"
  - scope:
      path: ""
      type: "pages"
    values:
      layout: "page"
  - scope:
      path: ""
      type: "posts"
    values:
      layout: "post"
  - scope:
      path: ""
      type: authors
    values:
      layout: "author2"


sass:
  sass_dir: _sass
  style: compressed